version: "3.1"
services:
  fantom-testnet:
    build:
      args:
        VERSION: release/1.1.3-rc.5
      context: ./fantom
      dockerfile: Dockerfile-testnet
    stop_grace_period: 3m
    environment:
      - CACHE_SIZE=${FANTOM_CACHE_SIZE:-16000}
    volumes:
      - "fantom-testnet:/datadir"
    expose:
      - "18544"
      - "44629"
    ports:
      - "44629:44629"
      - "44629:44629/udp"
    networks:
      - chains
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.fantom-testnet-stripprefix.stripprefix.prefixes=/fantom-testnet"
      - "traefik.http.services.fantom-testnet.loadbalancer.server.port=18544"
      - "traefik.http.routers.fantom-testnet.entrypoints=websecure"
      - "traefik.http.routers.fantom-testnet.tls.certresolver=myresolver"
      - "traefik.http.routers.fantom-testnet.rule=Host(`$DOMAIN`) && PathPrefix(`/fantom-testnet`)"
      - "traefik.http.routers.fantom-testnet.middlewares=fantom-testnet-stripprefix, ipwhitelist"

volumes:
  fantom-testnet:
